name: CI

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Flake8
        uses: py-actions/flake8@v2
        with:
          args: "--max-line-length=88 --max-complexity=10"

      - name: Run Bandit
        uses: jpetrucciani/bandit-check@main
        with:
          path: "."
          bandit_flags: "--skip B311,B101"

  selenium-tests:
    name: Selenium UI Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '2.1.1'

      - name: Install dependencies
        run: poetry install --with dev

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Run Streamlit app in background
        run: |
          poetry run streamlit run Sign_In.py --server.port 8501 &
          sleep 10

      - name: Run Pytest Selenium tests
        run: poetry run pytest tests/test_push_notifications.py
